#!/usr/bin/env bash
# swap-higgsfield-frames.sh <spin.mp4> <reveal.mp4>
# Run this once Higgsfield auth is fixed to replace placeholder frames
# with the real cinematic clips generated by Higgsfield.
set -e
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR/.."

echo "=== Morena Bijou · Higgsfield Frame Swap ==="
echo "Replacing placeholder frames with cinematic Higgsfield clips."
echo ""

SPIN_MP4="$1"; REVEAL_MP4="$2"
[ -z "$SPIN_MP4" ]   && { echo "Usage: $0 <spin.mp4> <reveal.mp4>"; exit 1; }
[ -z "$REVEAL_MP4" ] && { echo "Usage: $0 <spin.mp4> <reveal.mp4>"; exit 1; }

echo "[1/4] Backing up placeholder frames..."
cp -r frames/spin   frames/spin-placeholder   2>/dev/null || true
cp -r frames/reveal frames/reveal-placeholder 2>/dev/null || true

echo "[2/4] Extracting spin frames (180)..."
bash scripts/extract-frames.sh "$SPIN_MP4" frames/spin 180

echo "[3/4] Extracting reveal frames (180)..."
bash scripts/extract-frames.sh "$REVEAL_MP4" frames/reveal 180

echo "[4/4] Compressing frames (1600px, q88)..."
bash scripts/compress-frames.sh frames/spin   1600 88
bash scripts/compress-frames.sh frames/reveal 1600 88

echo ""
echo "Done. Reload the site to see your Higgsfield-generated cinematic frames."
echo "Placeholder backups kept in frames/spin-placeholder and frames/reveal-placeholder."
